project:
  type: website
  output-dir: docs

website:
  title: "ECON 355 - Regression"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - text: R Walkthroughs
        menu:
          - text: Lesson 1 - Getting Started
            href: 03_r_lectures/lecture_1_getting_started.qmd
          - text: Lesson 2 - Loading Data
            href: 03_r_lectures/lecture_2_loading_data.qmd
      - text: Labs
        menu: 
          - text: Lab 2
            href: 02_assignments/lab-02.qmd
          - text: Lab 3
            href: 02_assignments/lab-03.qmd
          - text: Lab 4
            href: 02_assignments/lab-04.qmd
          - text: Lab 5
            href: 02_assignments/lab-05.qmd
          - text: Lab 6
            href: 02_assignments/lab-06.qmd
          - text: Lab 7
            href: 02_assignments/lab-07.qmd
          - text: Lab 8
            href: 02_assignments/lab-08.qmd 
          - text: Lab 9
            href: 02_assignments/lab-09.qmd
          - text: Lab 10
            href: 02_assignments/lab-10.qmd
          - text: T Tests Mini Lab
            href: 02_assignments/mini_lab-ttests.qmd
      - text: Resources
        menu: 
          - text: Descriptive Statistics
            href: 00_descriptive/descriptives.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  echo: false
  error: false
  warning: false

